[package]
name = "physme"
version = "0.1.0"
authors = ["Szymon Walter <waltersz@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2"
smallvec = "1.4"
rstar = "0.8"
hashbrown = "0.9"